import type { AtlasIntent, AtlasModuleContext } from "@/lib/atlas/types"

export const atlasContexts: AtlasModuleContext[] = [
  { portal: "agency", key: "finance", label: "Financeiro", route: "/app/financeiro", summary: "Receitas, despesas, competência, parcelamento, recorrência e relatório financeiro." },
  { portal: "agency", key: "quotes", label: "Cotações", route: "/app/viagens/cotacoes", summary: "Propostas ligadas a cliente e viagem, com follow-up e resumo simples." },
  { portal: "agency", key: "itineraries", label: "Roteiros", route: "/app/viagens/roteiros", summary: "Roteiros manuais ligados a cliente e viagem, com leitura e download simples." },
  { portal: "agency", key: "trips", label: "Viagens", route: "/app/viagens", summary: "Operação da viagem, vínculo com cliente, documentos e compartilhamento público." },
  { portal: "agency", key: "contracts", label: "Contratos", route: "/app/documentos/contratos", summary: "Contratos separados do hub geral, com tipo padronizado e CRUD real." },
  { portal: "agency", key: "vouchers", label: "Vouchers", route: "/app/documentos/vouchers", summary: "Vouchers operacionais separados por tipo e voltados à viagem." },
  { portal: "agency", key: "receipts", label: "Recibos", route: "/app/documentos/recibos", summary: "Recibos separados do restante dos documentos, sem misturar com financeiro interno." },
  { portal: "agency", key: "tickets", label: "Passagens", route: "/app/documentos/passagens", summary: "Passagens e trechos emitidos, separados por tipo no hub documental." },
  { portal: "agency", key: "templates", label: "Templates", route: "/app/documentos/templates", summary: "Biblioteca de templates para documentos, relatórios e roteiros, sem misturar com operação comum." },
  { portal: "agency", key: "documents", label: "Documentos", route: "/app/documentos", summary: "Hub geral com contratos, vouchers, recibos, passagens e documentos gerais." },
  { portal: "agency", key: "catalog", label: "Catálogo", route: "/app/catalogo", summary: "Vitrine da agência, branding, pacotes e abertura pública do catálogo." },
  { portal: "agency", key: "match", label: "TravelPro Match", route: "/app/catalogo/travelpro-match", summary: "Expansão futura do marketplace, ainda em preparação sem backend real." },
  { portal: "agency", key: "credits", label: "Créditos", route: "/app/creditos", summary: "Saldo operacional, consumo recente e histórico básico dos créditos da agência." },
  { portal: "agency", key: "reports", label: "Relatórios", route: "/app/relatorios", summary: "Relatórios operacionais e financeiros com recorte real e exportações." },
  { portal: "agency", key: "tasks", label: "Tarefas", route: "/app/central-operacional/tarefas", summary: "Execução operacional com criação, edição, conclusão e exclusão." },
  { portal: "agency", key: "operational-center", label: "Central Operacional", route: "/app/central-operacional", summary: "Prioridades, feed vivo, tarefas, relatórios, insights e créditos." },
  { portal: "agency", key: "team", label: "Equipe", route: "/app/equipe", summary: "Membros, status e permissões visuais da equipe da agência." },
  { portal: "agency", key: "clients", label: "Clientes", route: "/app/clientes", summary: "Base real de clientes com criação, edição, busca e vínculo com viagens." },
  { portal: "agency", key: "leads", label: "Leads", route: "/app/leads", summary: "Pipeline comercial, qualificação, follow-up e conversão para cliente." },
  { portal: "agency", key: "dashboard", label: "Dashboard", route: "/app/dashboard", summary: "Visão executiva da agência com métricas reais e prioridades operacionais." },
  { portal: "agency", key: "go", label: "TravelPro Go", route: "/app/travelpro-go", summary: "Módulo em preparação para operação de WhatsApp, ainda sem integração real." },
  { portal: "agency", key: "agent", label: "TravelPro Agent", route: "/app/agent", summary: "Expansão futura para atendimento assistido, sem backend conversacional real." },
  { portal: "agency", key: "marketing", label: "Marketing IA", route: "/app/marketing", summary: "Módulo em preparação para campanhas e calendário promocional." },
  { portal: "agency", key: "advisor", label: "Atlas Advisor", route: "/app/atlas-advisor", summary: "Consultoria operacional guiada, ainda como expansão de suporte." },
  { portal: "agency", key: "automations", label: "Automações", route: "/app/automacoes", summary: "Fluxos em preparação, com espaço pronto para regras e históricos futuros." },
  { portal: "master", key: "master-dashboard", label: "Dashboard Master", route: "/master/dashboard", summary: "Cockpit executivo da plataforma com visão global por domínio." },
  { portal: "master", key: "master-agencies", label: "Agências", route: "/master/agencias", summary: "Base global de agências, plano, status, membros e atividade recente." },
  { portal: "master", key: "master-users", label: "Usuários", route: "/master/usuarios", summary: "Profiles, roles e status dos usuários na visão global do Master." },
  { portal: "master", key: "master-finance", label: "Financeiro Master", route: "/master/financeiro", summary: "Billing global da plataforma, separado do financeiro operacional das agências." },
  { portal: "master", key: "master-ai-credits", label: "IA e Créditos", route: "/master/ia-creditos", summary: "Consumo real de créditos, ranking por agência e visão de custos futuros." },
  { portal: "master", key: "master-reports", label: "Relatórios Master", route: "/master/relatorios", summary: "Histórico global de relatórios salvos e exportações por agência." },
  { portal: "master", key: "master-templates", label: "Templates Master", route: "/master/templates", summary: "Biblioteca oficial da plataforma para documentos, relatórios e roteiros." },
  { portal: "master", key: "master-logs", label: "Logs", route: "/master/logs", summary: "Audit logs e trilhas reais da plataforma quando existirem." },
  { portal: "master", key: "master-marketplace", label: "Marketplace", route: "/master/marketplace", summary: "Camada preparatória do Match com zero state honesto ou base pública real." },
  { portal: "master", key: "master-plans", label: "Planos", route: "/master/planos", summary: "Planos, add-ons e leitura comercial do SaaS." },
  { portal: "master", key: "master-whatsapp", label: "WhatsApp", route: "/master/whatsapp", summary: "Módulo em preparação para status por agência, logs e futura integração." },
]

export const atlasRouteContexts = [
  ["/app/central-operacional/creditos", "credits"],
  ["/app/central-operacional/relatorios", "reports"],
  ["/app/central-operacional/tarefas", "tasks"],
  ["/app/central-operacional/insights", "operational-center"],
  ["/app/central-operacional", "operational-center"],
  ["/app/documentos/templates", "templates"],
  ["/app/documentos/contratos", "contracts"],
  ["/app/documentos/vouchers", "vouchers"],
  ["/app/documentos/recibos", "receipts"],
  ["/app/documentos/passagens", "tickets"],
  ["/app/documentos", "documents"],
  ["/app/viagens/cotacoes", "quotes"],
  ["/app/viagens/roteiros", "itineraries"],
  ["/app/viagens", "trips"],
  ["/app/catalogo/travelpro-match", "match"],
  ["/app/catalogo", "catalog"],
  ["/app/creditos", "credits"],
  ["/app/relatorios", "reports"],
  ["/app/financeiro", "finance"],
  ["/app/equipe", "team"],
  ["/app/clientes", "clients"],
  ["/app/leads", "leads"],
  ["/app/travelpro-go", "go"],
  ["/app/atlas-advisor", "advisor"],
  ["/app/marketing", "marketing"],
  ["/app/automacoes", "automations"],
  ["/app/dashboard", "dashboard"],
  ["/app", "dashboard"],
  ["/master/ia-creditos", "master-ai-credits"],
  ["/master/relatorios", "master-reports"],
  ["/master/templates", "master-templates"],
  ["/master/financeiro", "master-finance"],
  ["/master/usuarios", "master-users"],
  ["/master/agencias", "master-agencies"],
  ["/master/logs", "master-logs"],
  ["/master/marketplace", "master-marketplace"],
  ["/master/planos", "master-plans"],
  ["/master/whatsapp", "master-whatsapp"],
  ["/master/atlas", "master-logs"],
  ["/master/dashboard", "master-dashboard"],
  ["/master", "master-dashboard"],
] as const

export const atlasIntents: AtlasIntent[] = [
  {
    id: "agency-create-trip",
    portal: "agency",
    module: "trips",
    title: "Criar viagem",
    keywords: ["criar viagem", "nova viagem", "como criar viagem", "abrir viagem"],
    quickQuestions: ["Como criar uma viagem?", "Como vincular cliente na viagem?"],
    route: "/app/viagens/nova",
    routeLabel: "Abrir nova viagem",
    status: "ready",
    summary: "Use o workspace de viagens para cadastrar destino, período, status e vínculos com cliente.",
    bullets: [
      "Abra Viagens e use o CTA Nova viagem.",
      "O formulário já trabalha com selects reais de cliente e salva no Supabase.",
      "Depois de salvar, a viagem aparece na listagem e alimenta dashboard e central operacional.",
    ],
    nextSteps: ["Se precisar de proposta, siga para Cotações.", "Se a viagem for confirmada, gere o link compartilhável em seguida."],
  },
  {
    id: "agency-share-trip",
    portal: "agency",
    module: "trips",
    title: "Compartilhar viagem",
    keywords: ["compartilhar viagem", "copiar link da viagem", "link publico viagem", "v token", "portal cliente moderno"],
    quickQuestions: ["Como compartilhar viagem?", "Como desativar o link da viagem?"],
    route: "/app/viagens",
    routeLabel: "Abrir viagens",
    status: "ready",
    summary: "O compartilhamento público da viagem usa um link seguro em `/v/[token]` e não exige login do cliente.",
    bullets: [
      "Na lista de viagens, use Compartilhar viagem para gerar ou reutilizar o link ativo.",
      "Copiar link e Abrir link usam a experiência pública mobile-first do cliente.",
      "Desativar link interrompe o acesso público e mantém a viagem interna intacta.",
    ],
    nextSteps: ["Se quiser testar, abra o link em aba anônima.", "Use o Atlas para orientar a equipe sobre esse fluxo."],
  },
  {
    id: "agency-finance-expense",
    portal: "agency",
    module: "finance",
    title: "Lançar despesa",
    keywords: ["lancar despesa", "lançar despesa", "nova despesa", "despesa", "receita", "financeiro"],
    quickQuestions: ["Como lançar despesa?", "Como parcelar um lançamento?"],
    route: "/app/financeiro/novo",
    routeLabel: "Abrir novo lançamento",
    status: "ready",
    summary: "O financeiro usa competência real e permite valor único, parcelado ou recorrente mensal.",
    bullets: [
      "Preencha tipo, categoria, valor, status, competência e vencimento quando houver.",
      "Parcelado cria vários registros futuros; recorrência mensal gera lançamentos por período.",
      "Os filtros da tela usam o recorte real por competência em vez de prender tudo ao mês atual.",
    ],
    nextSteps: ["Se quiser leitura executiva, gere o relatório a partir do recorte atual.", "Registrar pagamento atualiza o lançamento sem sair da operação."],
  },
  {
    id: "agency-finance-filters",
    portal: "agency",
    module: "finance",
    title: "Filtros do financeiro",
    keywords: ["filtro financeiro", "hoje semana mes trimestre ano", "a receber", "pendente", "competencia"],
    quickQuestions: ["Como funcionam os filtros do financeiro?", "Como gerar relatório com esse recorte?"],
    route: "/app/financeiro",
    routeLabel: "Abrir financeiro",
    status: "ready",
    summary: "Os filtros financeiros respeitam a data de competência do lançamento e os recortes atuais da tela.",
    bullets: [
      "Hoje, Semana, Mês, Trimestre, Ano e Personalizado usam a data do lançamento.",
      "Receita, Despesa, A receber e Pendente funcionam sobre o status e tipo real do lançamento.",
      "O relatório financeiro herda automaticamente o filtro atual do módulo.",
    ],
    nextSteps: ["Use Personalizado quando quiser um recorte fechado.", "Depois disso, gere o relatório sem preencher tudo de novo."],
  },
  {
    id: "agency-reports",
    portal: "agency",
    module: "reports",
    title: "Gerar relatório",
    keywords: ["gerar relatorio", "exportar relatorio", "relatorio financeiro", "relatorios", "baixar html", "pdf"],
    quickQuestions: ["Como gerar relatório?", "Como exportar PDF e HTML?"],
    route: "/app/relatorios",
    routeLabel: "Abrir relatórios",
    status: "ready",
    summary: "Os relatórios operacionais usam dados reais, recorte por período e exportação HTML/PDF no fluxo atual.",
    bullets: [
      "A tela Novo relatório deixa escolher tipo, período e exportação sem repetir campos desnecessários.",
      "No financeiro, o CTA de relatório já carrega o filtro atual da sessão.",
      "Relatórios salvos podem ser reabertos, regenerados e baixados novamente.",
    ],
    nextSteps: ["Se quiser PDF, use o exportador do relatório salvo.", "Se o recorte estiver na tela financeira, gere por lá para herdar o contexto."],
  },
  {
    id: "agency-quote",
    portal: "agency",
    module: "quotes",
    title: "Criar cotação",
    keywords: ["criar cotacao", "criar cotação", "nova cotacao", "nova cotação", "proposta simples"],
    quickQuestions: ["Como criar cotação?", "Como registrar follow-up da cotação?"],
    route: "/app/viagens/cotacoes/nova",
    routeLabel: "Abrir nova cotação",
    status: "ready",
    summary: "Cotações ficam separadas de viagens e documentos, mas usam a mesma base padronizada com tipo canônico.",
    bullets: [
      "Use Nova cotação para abrir o workspace correto.",
      "A cotação pode ser vinculada a cliente e viagem quando houver relacionamento disponível.",
      "Depois de salvar, ela aparece em /app/viagens/cotacoes e permite follow-up e download simples.",
    ],
    nextSteps: ["Se a proposta evoluir, siga para contrato ou roteiro.", "Evite abrir pelo hub de documentos quando a intenção for comercial."],
  },
  {
    id: "agency-itinerary",
    portal: "agency",
    module: "itineraries",
    title: "Criar roteiro",
    keywords: ["criar roteiro", "novo roteiro", "baixar roteiro", "roteiro manual"],
    quickQuestions: ["Como criar roteiro?", "Como baixar o resumo do roteiro?"],
    route: "/app/viagens/roteiros/novo",
    routeLabel: "Abrir novo roteiro",
    status: "ready",
    summary: "Roteiros ficam em Viagens > Roteiros e aparecem na listagem logo após salvar com o tipo padronizado.",
    bullets: [
      "O roteiro pode ser ligado à viagem e ao cliente no mesmo fluxo.",
      "Editar, visualizar, excluir e baixar resumo simples já fazem parte da operação atual.",
      "A geração com IA ainda é futura; por agora o Atlas só orienta o fluxo manual.",
    ],
    nextSteps: ["Se a viagem for pública, use o roteiro também na experiência compartilhável.", "Documentos de apoio podem ser anexados no hub documental."],
  },
  {
    id: "agency-documents",
    portal: "agency",
    module: "documents",
    title: "Hub de documentos",
    keywords: ["documentos", "contrato voucher recibo passagem", "diferenca documentos", "hub documental"],
    quickQuestions: ["Qual a diferença entre contratos, vouchers e recibos?", "Como abrir o hub de documentos?"],
    route: "/app/documentos",
    routeLabel: "Abrir documentos",
    status: "ready",
    summary: "O hub geral de documentos mostra os tipos operacionais padronizados sem misturar roteiros, cotações e templates.",
    bullets: [
      "Contratos, vouchers, recibos e passagens têm subpáginas próprias e filtros consistentes.",
      "Templates ficam separados da operação comum em /app/documentos/templates.",
      "Roteiros e cotações pertencem ao módulo de Viagens, não ao hub documental geral.",
    ],
    nextSteps: ["Use a subpágina específica quando já souber o tipo do documento.", "Se quiser reusar um modelo, vá para Templates."],
  },
  {
    id: "agency-templates",
    portal: "agency",
    module: "templates",
    title: "Templates",
    keywords: ["template", "usar template", "biblioteca template", "ativar template"],
    quickQuestions: ["Como funciona a biblioteca de templates?", "Como usar template como base?"],
    route: "/app/documentos/templates",
    routeLabel: "Abrir templates",
    status: "ready",
    summary: "Templates ficam numa biblioteca própria e podem ser ativados, editados e usados como base sem misturar com documentos do dia a dia.",
    bullets: [
      "A tela lista apenas templates, não contratos ou vouchers operacionais.",
      "Usar como base abre o fluxo já pré-preenchido para agilizar a criação.",
      "Ativar ou desativar controla disponibilidade interna da biblioteca.",
    ],
    nextSteps: ["Se quiser identidade institucional, ajuste branding no fluxo correspondente.", "Templates inteligentes com IA continuam em preparação."],
  },
  {
    id: "agency-catalog",
    portal: "agency",
    module: "catalog",
    title: "Catálogo e vitrine pública",
    keywords: ["catalogo", "vitrine publica", "branding", "publicar pacote", "abrir vitrine", "link publico catalogo"],
    quickQuestions: ["Como publicar um pacote?", "Como abrir a vitrine pública da agência?"],
    route: "/app/catalogo",
    routeLabel: "Abrir catálogo",
    status: "ready",
    summary: "O catálogo controla branding, pacotes e a vitrine pública da agência em `/catalogo/[slug]`.",
    bullets: [
      "Pacotes publicados aparecem na vitrine pública; rascunhos e inativos ficam só no painel interno.",
      "Logo, banner e identidade visual podem ser salvos na configuração pública do catálogo.",
      "TravelPro Match continua separado como expansão futura e não substitui a vitrine atual.",
    ],
    nextSteps: ["Se o pacote estiver pronto, publique e abra a vitrine pública.", "Se quiser distribuição futura, acompanhe o módulo Match."],
  },
  {
    id: "agency-credits",
    portal: "agency",
    module: "credits",
    title: "Créditos",
    keywords: ["creditos", "consumo de creditos", "saldo de creditos", "historico de creditos"],
    quickQuestions: ["Como ver o consumo de créditos?", "Qual a diferença entre saldo e consumo?"],
    route: "/app/creditos",
    routeLabel: "Abrir créditos",
    status: "ready",
    summary: "Créditos mostram saldo operacional, histórico e origem do consumo sem depender de Stripe nesta etapa.",
    bullets: [
      "O saldo vem da base real de transações de créditos da agência.",
      "A Central Operacional também mostra o recorte vivo de consumo.",
      "Compra de créditos ainda está em breve; a leitura operacional já está pronta.",
    ],
    nextSteps: ["Se quiser histórico junto da operação, abra a Central Operacional > Créditos.", "A compra segura será conectada depois."],
  },
  {
    id: "agency-team",
    portal: "agency",
    module: "team",
    title: "Equipe",
    keywords: ["equipe", "convidar membro", "status da equipe", "permissoes equipe"],
    quickQuestions: ["Como adicionar alguém à equipe?", "O convite por e-mail já está ativo?"],
    route: "/app/equipe",
    routeLabel: "Abrir equipe",
    status: "ready",
    summary: "Equipe já lista membros, status e edição básica. Convite real por e-mail ainda está em preparação.",
    bullets: [
      "Você pode criar e editar membros no fluxo atual.",
      "Status e permissões visuais já ficam disponíveis na listagem.",
      "O CTA de convite é honesto: ele avisa que o fluxo avançado de auth vem depois.",
    ],
    nextSteps: ["Para cadastro imediato, use Adicionar membro.", "Para convite automático, aguarde a fase de auth avançada."],
  },
  {
    id: "agency-future-go",
    portal: "agency",
    module: "go",
    title: "TravelPro Go",
    keywords: ["travelpro go", "go", "whatsapp operacional"],
    quickQuestions: ["O TravelPro Go já está ativo?", "O Go já conversa com WhatsApp real?"],
    route: "/app/travelpro-go",
    routeLabel: "Abrir TravelPro Go",
    status: "future",
    summary: "O TravelPro Go é um módulo em preparação e ainda não está conectado ao WhatsApp real nesta etapa.",
    bullets: [
      "A interface existe para orientar a operação e o posicionamento do produto.",
      "Logs, histórico e ações ainda usam estado honesto de preparação.",
      "Quando a integração real entrar, o Atlas vai passar a explicar o fluxo operacional completo.",
    ],
    nextSteps: ["Hoje vale tratar o Go como expansão futura.", "Para mensagens reais, aguarde a fase dedicada de WhatsApp."],
  },
  {
    id: "agency-future-match",
    portal: "agency",
    module: "match",
    title: "TravelPro Match",
    keywords: ["match", "marketplace", "travelpro match"],
    quickQuestions: ["O Match já distribui pacotes reais?", "Qual a diferença entre catálogo e Match?"],
    route: "/app/catalogo/travelpro-match",
    routeLabel: "Abrir Match",
    status: "future",
    summary: "O Match é uma expansão futura do ecossistema. Hoje ele permanece como camada de preparação, não como operação real.",
    bullets: [
      "Catálogo e vitrine pública da agência já funcionam agora.",
      "Match, impulsionamento e distribuição comercial ainda não têm backend real nesta fase.",
      "O Atlas sempre explica Match como expansão futura, sem prometer entrega já ativa.",
    ],
    nextSteps: ["Use o catálogo para publicar hoje.", "Acompanhe o Match só como preparação de produto por enquanto."],
  },
  {
    id: "shared-public-trip",
    portal: "all",
    module: "trips",
    title: "Experiência compartilhável da viagem",
    keywords: ["v token", "experiencia compartilhavel", "portal cliente moderno", "pagina publica viagem", "sem login"],
    quickQuestions: ["Como funciona o link público da viagem?", "O cliente precisa fazer login?"],
    route: "/app/viagens",
    routeLabel: "Abrir viagens",
    status: "ready",
    summary: "A experiência pública da viagem em `/v/[token]` é o novo formato principal para o cliente final, sem login.",
    bullets: [
      "Ela mostra destino, período, status, roteiro público, documentos seguros e contato da agência.",
      "O cliente só abre o link; não precisa conta nem acesso ao portal legado.",
      "Se o link for desativado ou expirar, a página mostra um estado elegante de indisponibilidade.",
    ],
    nextSteps: ["Use Compartilhar viagem no módulo de Viagens.", "Teste em aba anônima para validar o que o cliente verá."],
  },
  {
    id: "master-agencies",
    portal: "master",
    module: "master-agencies",
    title: "Agências no Master",
    keywords: ["agencias master", "ver agencias", "editar agencia", "membros da agencia"],
    quickQuestions: ["Como revisar uma agência no Master?", "Onde vejo consumo e membros da agência?"],
    route: "/master/agencias",
    routeLabel: "Abrir agências",
    status: "ready",
    summary: "No Master, Agências traz a visão global de contas, planos, membros, consumo e atividade recente.",
    bullets: [
      "A listagem usa dados reais de agencies, members e activity quando disponíveis.",
      "Editar e ativar/inativar funciona quando o campo compatível existe no schema atual.",
      "Essa visão é global e não deve ser confundida com a operação isolada do portal da agência.",
    ],
    nextSteps: ["Abra o detalhe da agência para membros e consumo.", "Se a dúvida for billing da plataforma, vá para Financeiro Master."],
  },
  {
    id: "master-finance",
    portal: "master",
    module: "master-finance",
    title: "Financeiro Master",
    keywords: ["financeiro master", "pagamentos master", "billing master", "receita plataforma"],
    quickQuestions: ["Qual a diferença entre Financeiro Master e Financeiro da agência?", "Onde vejo pagamentos da plataforma?"],
    route: "/master/financeiro",
    routeLabel: "Abrir financeiro Master",
    status: "ready",
    summary: "O Financeiro Master mostra billing global da plataforma e não deve misturar lançamentos operacionais das agências.",
    bullets: [
      "A leitura global usa payments, subscriptions, créditos vendidos e sinais de cobrança.",
      "O financeiro da agência continua isolado no tenant, com receitas e despesas operacionais.",
      "Stripe real e cobrança automática ainda estão fora desta etapa.",
    ],
    nextSteps: ["Se a dúvida for sobre uma agência específica, abra Agências.", "Se precisar de exportação avançada, use Relatórios Master."],
  },
  {
    id: "master-ai-credits",
    portal: "master",
    module: "master-ai-credits",
    title: "IA e Créditos",
    keywords: ["ia creditos", "consumo de creditos master", "logs ia", "custos ia"],
    quickQuestions: ["O Master já tem custo real de IA?", "Onde vejo ranking de consumo por agência?"],
    route: "/master/ia-creditos",
    routeLabel: "Abrir IA e créditos",
    status: "ready",
    summary: "IA e Créditos no Master já lê transações reais de créditos e ranking por agência, mas sem OpenAI real nesta fase.",
    bullets: [
      "Consumo e histórico vêm da base real de créditos.",
      "Custos monetários detalhados de IA ainda dependem da integração futura com a camada real de execução.",
      "Logs IA mostram apenas sinais reais disponíveis, sem inventar atividade sintética.",
    ],
    nextSteps: ["Abra Logs IA para sinais disponíveis.", "Trate OpenAI real como próxima fase, não como entrega atual."],
  },
  {
    id: "master-reports",
    portal: "master",
    module: "master-reports",
    title: "Relatórios Master",
    keywords: ["relatorios master", "historico de relatorios", "exportar relatorio master", "templates master"],
    quickQuestions: ["Como abrir um relatório salvo no Master?", "Como funcionam os templates oficiais?"],
    route: "/master/relatorios",
    routeLabel: "Abrir relatórios Master",
    status: "ready",
    summary: "Relatórios Master consolidam históricos globais e permitem abrir, regenerar e exportar relatórios salvos.",
    bullets: [
      "A listagem identifica agência, tipo, status, origem e data.",
      "Exportação e regeneração reaproveitam o motor real de relatórios.",
      "Templates oficiais ficam em módulo separado para evitar mistura entre biblioteca e histórico.",
    ],
    nextSteps: ["Se a dúvida for sobre modelos, abra Templates Master.", "Se a dúvida for execução financeira, use Financeiro Master."],
  },
  {
    id: "master-whatsapp",
    portal: "master",
    module: "master-whatsapp",
    title: "WhatsApp no Master",
    keywords: ["whatsapp master", "instancia whatsapp", "webhook whatsapp", "conectar whatsapp"],
    quickQuestions: ["O WhatsApp Master já está conectado?", "O que esse módulo mostra hoje?"],
    route: "/master/whatsapp",
    routeLabel: "Abrir WhatsApp",
    status: "future",
    summary: "O módulo WhatsApp do Master está pronto visualmente e operacionalmente para leitura, mas a integração real ainda não foi ativada.",
    bullets: [
      "Ele usa sinais reais quando houver metadata, notifications ou audit logs compatíveis.",
      "Conectar instância, testar conexão e configurar webhook continuam como próximas etapas.",
      "O Atlas sempre trata esse módulo como preparação honesta, não como conexão ativa.",
    ],
    nextSteps: ["Use a tela para leitura de sinais e status.", "Para integração real, aguarde a fase dedicada de WhatsApp."],
  },
]
