create index if not exists agencies_status_idx on public.agencies(status);
create index if not exists profiles_agency_id_idx on public.profiles(agency_id);
create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists agency_members_agency_id_idx on public.agency_members(agency_id);
create index if not exists agency_members_profile_id_idx on public.agency_members(profile_id);
create index if not exists clients_agency_id_idx on public.clients(agency_id);
create index if not exists clients_profile_id_idx on public.clients(profile_id);
create index if not exists leads_agency_id_idx on public.leads(agency_id);
create index if not exists leads_client_id_idx on public.leads(client_id);
create index if not exists trips_agency_id_idx on public.trips(agency_id);
create index if not exists trips_client_id_idx on public.trips(client_id);
create index if not exists itineraries_agency_id_idx on public.itineraries(agency_id);
create index if not exists itineraries_trip_id_idx on public.itineraries(trip_id);
create index if not exists documents_agency_id_idx on public.documents(agency_id);
create index if not exists documents_trip_id_idx on public.documents(trip_id);
create index if not exists catalog_items_agency_id_idx on public.catalog_items(agency_id);
create index if not exists team_members_agency_id_idx on public.team_members(agency_id);
create index if not exists financial_records_agency_id_idx on public.financial_records(agency_id);
create index if not exists financial_records_occurred_at_idx on public.financial_records(occurred_at desc);
create index if not exists subscriptions_agency_id_idx on public.subscriptions(agency_id);
create index if not exists payments_agency_id_idx on public.payments(agency_id);
create index if not exists credit_transactions_agency_id_idx on public.credit_transactions(agency_id);
create index if not exists notifications_agency_id_idx on public.notifications(agency_id);
create index if not exists notifications_profile_id_idx on public.notifications(profile_id);
create index if not exists tasks_agency_id_idx on public.tasks(agency_id);
create index if not exists reports_agency_id_idx on public.reports(agency_id);
create index if not exists audit_logs_agency_id_idx on public.audit_logs(agency_id);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity, entity_id);
